apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: default
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      hostname: eureka
      containers:
      - name: eureka
        image: openjdk
        imagePullPolicy: Never
        command: ["sh"]
        args: ["-c", "java -jar /app/discover-0.0.1-SNAPSHOT.jar"]
        volumeMounts:
        - mountPath: /app/discover-0.0.1-SNAPSHOT.jar
          name: test-volume
      volumes:
      - name: test-volume
        hostPath:
          path: /data/discover-0.0.1-SNAPSHOT.jar
          type: File