apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: default
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      hostname: gateway
      containers:
      - name: gateway
        image: openjdk
        imagePullPolicy: Never
        command: ["sh"]
        args: ["-c", "java -jar /app/api-gateway-0.0.1-SNAPSHOT.jar"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /app/api-gateway-0.0.1-SNAPSHOT.jar
          name: test-volume
      volumes:
      - name: test-volume
        hostPath:
          path: /data/api-gateway-0.0.1-SNAPSHOT.jar
          type: File
