apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  namespace: default
  labels:
    app: reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      hostname: reviews
      containers:
      - name: reviews
        image: openjdk
        imagePullPolicy: Never
        command: ["sh"]
        args: ["-c", "java -jar /app/demo-0.0.1-SNAPSHOT.jar"]
        volumeMounts:
        - mountPath: /app/demo-0.0.1-SNAPSHOT.jar
          name: test-volume
      volumes:
      - name: test-volume
        hostPath:
          path: /data/demo-0.0.1-SNAPSHOT.jar
          type: File