apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Klasser\SystemIntegration\Microservices\Deploy\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: eureka
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eureka
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Klasser\SystemIntegration\Microservices\Deploy\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: eureka
    spec:
      containers:
      - args:
        - sh
        - -c
        - java -jar discover-0.0.1-SNAPSHOT.jar
        image: openjdk
        imagePullPolicy: ""
        name: eureka
        resources: {}
        workingDir: /app
        volumeMounts:
        - mountPath: /app
          name: test-volume
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: test-volume
        hostPath:
          path: 'D:\Klasser\SystemIntegration\Microservices\Deploy\'
status: {}
