apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Klasser\SystemIntegration\Microservices\Deploy\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Klasser\SystemIntegration\Microservices\Deploy\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
    spec:
      containers:
      - args:
        - sh
        - -c
        - java -jar api-gateway-0.0.1-SNAPSHOT.jar
        image: openjdk
        imagePullPolicy: ""
        name: gateway
        ports:
        - containerPort: 8080
        resources: {}
        workingDir: /app
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
