apiVersion: apps/v1
kind: Deployment
metadata:
metadata:
  name: mongodb
  labels:
    app: cars
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cars
  template:
    metadata:
      labels:
        app: cars
    spec:
      containers:
      - name: mongodb
        image: mongo
        imagePullPolicy: Never
      restartPolicy: Never