apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      
apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  selector:
    app: eureka 
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
 