apiVersion: apps/v1
kind: Deployment
metadata:
  name: net
  labels:
    app: cars
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cars
  template:
    metadata:
      labels:
        app: cars
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        imagePullPolicy: Never